# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
    - pipeline: buildContosAir # identifier for the resource used in pipeline resource variables
      source: 'Joe-Code.ContosoAir GitHub Lab 1-31-2022' # name of the pipeline that produces an artifact

      trigger:
        branches:
          include:
            - master
pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '5e236c1e-cf37-4b0d-b04a-b19e8bd19f22'
    definition: '41'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AIRS-JFitzgerald(45754f4f-6e9d-416a-92b1-758bff5a564f)'
    subscriptionId: '45754f4f-6e9d-416a-92b1-758bff5a564f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourcegroup)'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
    csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
    overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
    deploymentMode: 'Incremental'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'AIRS-JFitzgerald(45754f4f-6e9d-416a-92b1-758bff5a564f)'
    appType: 'webApp'
    WebAppName: 
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
